Changes for using new CoreBundle installationService
ConductionNL/commonground-gateway pull request #1355
Opened 2023-02-27 13:49 UTC by WilcoLouwerse

2023-02-27 14:01 UTC, rubenvdlinde requested changes
Small doc boc clearups are in order, but setting the gateway to dev feels like a no no

2023-02-27 14:01 UTC, rjzondervan requested changes

2023-02-27 14:01 UTC, rubenvdlinde commented on api/src/Entity/Gateway.php
> +     * @throws GatewayException
Does it? and what about a return?

2023-02-27 14:01 UTC, rjzondervan commented on api/src/Entity/Gateway.php
> +    private ?array $configuration = ["verify" => false];
This is not something I would necessarily default. Yes, it happens quite often, but I don't think it should be a default

2023-02-27 15:02 UTC, WilcoLouwerse commented on api/composer.json
> +    "minimum-stability": "dev",
Can't we somehow set it to dev on the development branch and stable on the master branch?

2023-02-27 15:05 UTC, WilcoLouwerse commented on api/src/Entity/Gateway.php
> +    private ?array $configuration = ["verify" => false];
Why not, in my experience it does happen more often than it doesn't?

2023-02-27 15:09 UTC, WilcoLouwerse commented on api/src/Entity/CollectionEntity.php
> +
What is the fastest/easiest way to do this?

2023-02-27 15:11 UTC, rubenvdlinde commented on api/composer.json
> +    "minimum-stability": "dev",
Do we want to? It has a high risk of ending up on main that way. And this is the core repository that we are talking about so als dependencies schould be external (non-conduction) why should we want te develop on external dev libraries with the change that they break on main in the case of differences?

2023-02-27 15:11 UTC, rjzondervan commented on api/src/Entity/Gateway.php
> +    private ?array $configuration = ["verify" => false];
Because it in the end is a security issue you're bypassing. So even if we would have to do it for _all_ sources, I want the person configuring it to be aware of what they are doing.

2023-02-27 15:13 UTC, rubenvdlinde commented on api/src/Entity/CollectionEntity.php
> +
https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#generating-migrations-automatically

2023-02-27 15:25 UTC, WilcoLouwerse commented on api/composer.json
> +    "minimum-stability": "dev",
True, it is just convenient if we want to test with specific branches on a bundle, because that won't work with "stable".
But if it isn't easy to do we can always locally change this to dev while testing, still with the risk of someone pushing / merging it to development or master

2023-02-27 15:26 UTC, rjzondervan commented on api/composer.json
> +    "minimum-stability": "dev",
I'd opt for not tuning down minimum stability in committed code. If we need to in our local environment to run tests fine, but I'd refrain from changing it in committed code.

2023-02-27 15:38 UTC, WilcoLouwerse commented on api/src/Entity/CollectionEntity.php
> +
Generated a migration with
php bin/console doctrine:migrations:diff
Not sure if it is correct though

2023-02-28 08:18 UTC, rjzondervan requested changes

2023-03-01 09:02 UTC, rubenvdlinde requested changes
Some minor remarks

2023-03-01 09:02 UTC, rubenvdlinde commented on api/symfony.lock
> +    "larping-base/larping-bundle": {
Ahum

2023-03-01 09:26 UTC, rubenvdlinde approved these changes
Tops

2023-03-01 09:35 UTC, rjzondervan approved these changes

2023-03-01 09:35 UTC, merged