Subscribers removed
ConductionNL/commonground-gateway pull request #1517
Opened 2023-06-30 14:10 UTC by bbrands02

2023-06-30 14:12 UTC, WilcoLouwerse requested changes

2023-06-30 14:12 UTC, WilcoLouwerse commented on api/composer.json
> +        "commongateway/corebundle": "<1.1.22",
we used < becase we did not want to install the gateway with a higher CoreBundle version than 1.1
You need to use ^ instead to require minimum version instead

2023-06-30 14:13 UTC, rjzondervan requested changes

2023-06-30 14:13 UTC, rjzondervan commented on api/composer.json
> +        "commongateway/corebundle": "<1.1.22",
This can become ^1.1.22 for this version, <1.1 was to prevent master images from using a version higher than 1.0.107

2023-06-30 14:13 UTC, bbrands02 commented on api/composer.json
> +        "commongateway/corebundle": "<1.1.22",
my bad

2023-06-30 14:15 UTC, rjzondervan approved these changes

2023-07-10 10:43 UTC, WilcoLouwerse approved these changes

2023-07-10 10:43 UTC, merged