Changes for federative requests
ConductionNL/commonground-gateway pull request #1623
Opened 2024-03-12 15:46 UTC by rjzondervan

2024-03-12 16:01 UTC, WilcoLouwerse requested changes

2024-03-12 16:01 UTC, WilcoLouwerse commented on api/migrations/Version20240311121033.php
> +        $this->addSql('ALTER TABLE action ALTER id TYPE UUID');
Please remove uuid stuff from migrations

2024-03-12 16:01 UTC, WilcoLouwerse commented on api/migrations/Version20240311125549.php
> +        $this->addSql('ALTER TABLE action ALTER id TYPE UUID');
Please remove uuid stuff from migrations

2024-03-12 16:01 UTC, WilcoLouwerse commented on api/migrations/Version20240311132843.php
> +        $this->addSql('ALTER TABLE action ALTER id TYPE UUID');
Please remove uuid stuff from migrations

2024-03-12 16:01 UTC, WilcoLouwerse commented on api/src/Entity/Endpoint.php
> +    private $federationProxies;
Do we want a default value here? maybe null / empty array?

And what about @var & @MaxDepth 🤔

2024-03-12 16:01 UTC, WilcoLouwerse commented on api/src/Entity/Gateway.php
> +    private $federationEndpoints;
Do we want a default value here? maybe null / empty array?

And what about @var & @MaxDepth 🤔

2024-03-12 16:08 UTC, rjzondervan commented on api/src/Entity/Endpoint.php
> +    private $federationProxies;
Default value is set by the constructor.
Will add documentation in the morning

2024-03-13 23:08 UTC, WilcoLouwerse approved these changes

2024-03-14 11:09 UTC, bbrands02 approved these changes

2024-03-14 11:14 UTC, merged