Added multi tenant object databases
ConductionNL/commonground-gateway pull request #1625
Opened 2024-03-15 14:06 UTC by WilcoLouwerse

2024-03-15 14:19 UTC, rjzondervan requested changes
Looks generally alright, but please add type hints _everywhere_

2024-03-15 14:19 UTC, rjzondervan commented on api/src/Entity/Database.php
> +    private $dateModified;
Please make this DateTimeInterface-instances with type hint, see for example the Contract entity

2024-03-15 14:19 UTC, rjzondervan commented on api/src/Entity/Database.php
> +    private $id;
UuidInterface please :), see the File entity

2024-03-15 14:56 UTC, bbrands02 approved these changes, later dismissed

2024-03-15 15:04 UTC, WilcoLouwerse commented on api/src/Entity/Database.php
> +    private $dateModified;
will do

2024-03-15 15:05 UTC, WilcoLouwerse commented on api/src/Entity/Database.php
> +    private $id;
will do

2024-03-18 08:55 UTC, rjzondervan requested changes

2024-03-18 08:55 UTC, rjzondervan commented on api/src/Entity/Database.php
> +    }
You're missing a docblock here, and shouldn't this be _after_ the constructor

2024-03-18 11:22 UTC, rjzondervan approved these changes

2024-03-18 11:29 UTC, merged