Working basecase, dependent on ObjectEntityService refactor
ConductionNL/commonground-gateway pull request #701
Opened 2022-08-11 11:42 UTC by rjzondervan

2022-08-11 12:25 UTC, smisidjan commented on api/src/ActionHandler/ZaakTypeHandler.php
> +        var_dump(count($objectEntities));
Here you forgot to delete a var_dump

2022-08-11 12:27 UTC, rjzondervan commented on api/src/ActionHandler/ZaakTypeHandler.php
> +        var_dump(count($objectEntities));
Well spotted, thanks! Fixed it now :)

2022-08-11 12:28 UTC, smisidjan approved these changes

2022-08-11 13:16 UTC, WilcoLouwerse requested changes

2022-08-11 13:16 UTC, WilcoLouwerse commented on api/src/Service/SynchronizationService.php
>              // todo: set organization and application for $object, see eavService->getObject() function.
Are you sure this works without setting the organization and application (from the session, see eavService->getObject()) ?

2022-08-11 13:16 UTC, WilcoLouwerse commented on api/src/Service/SynchronizationService.php
> -        // What if the source has no property that allows us to determine the last change
Removing to many of these comments will make the code less readable and understandable, would not recommend doing this, even if the result is less lines of text/code...

2022-08-11 13:16 UTC, WilcoLouwerse commented on api/src/Service/SynchronizationService.php
> +        if ($validationErrors = $this->validatorService->validateData($data, $objectEntity->getEntity(), 'POST')) {
What are we going to do with validationErrors?

2022-08-11 13:16 UTC, WilcoLouwerse commented on api/src/Service/SynchronizationService.php
>              // todo: set organization and application for $object, see eavService->getObject() function.
I think even the saveObject route from the objectEntityService might not do this. Are we sure the org. and appl. of the main object (not subObjects!) are set before we persist and flush this object?

2022-08-11 13:23 UTC, rjzondervan commented on api/src/Service/SynchronizationService.php
> -        // What if the source has no property that allows us to determine the last change
Partially agree, sometimes a comment is necessary, but if the internals of the code are obvious, adding comments about it only decreases the readability of the code.

2022-08-11 13:24 UTC, rjzondervan commented on api/src/Service/SynchronizationService.php
> +        if ($validationErrors = $this->validatorService->validateData($data, $objectEntity->getEntity(), 'POST')) {
I left that open for now indeed, it is something we need to look into, but I recommend putting it in logs.

2022-08-15 09:39 UTC, WilcoLouwerse commented on api/src/Service/SynchronizationService.php
> +        if ($validationErrors = $this->validatorService->validateData($data, $objectEntity->getEntity(), 'POST')) {
add a nice todo for this?

2022-08-15 09:39 UTC, WilcoLouwerse commented on api/src/Service/SynchronizationService.php
> +        $application = $this->entityManager->getRepository('App:Application')->findOneBy(['name' => 'main application']);
Else, if only one application exists, use that one

2022-08-15 10:42 UTC, WilcoLouwerse approved these changes

2022-08-15 10:46 UTC, merged