Bring 1107-intermediatestatus to main branch for the feature
ConductionNL/commonground-gateway pull request #702
Opened 2022-08-11 11:45 UTC by rjzondervan

2022-08-11 12:41 UTC, smisidjan requested changes

2022-08-11 12:41 UTC, smisidjan commented on api/src/Service/ResponseService.php
> +                    }
This are a lot of nested levels

2022-08-11 12:49 UTC, rjzondervan commented on api/src/Service/ResponseService.php
> +                    }
@WilcoLouwerse Is this something you refactor quickly, or do I have to look into it?

2022-08-11 13:27 UTC, WilcoLouwerse approved these changes
Read my comments please before merging ;)
And make sure synchronization.php is updated, this is an old version of the file/entity

2022-08-11 13:27 UTC, WilcoLouwerse commented on api/src/Entity/Action.php
> +    private array $throws = [];
?array want nullable=true ?

2022-08-11 13:27 UTC, WilcoLouwerse commented on api/src/Entity/Action.php
> +    private array $conditions = [];
?array want nullable=true ?

2022-08-11 13:27 UTC, WilcoLouwerse commented on api/src/Entity/Action.php
> +    private array $configuration = [];
?array want nullable=true ?

2022-08-11 13:27 UTC, WilcoLouwerse commented on api/src/Entity/Synchronization.php
> +     * @ORM\OneToOne(targetEntity=Entity::class, cascade={"persist", "remove"})
Should be manyToOne and pls no cascading here!

2022-08-11 13:27 UTC, WilcoLouwerse commented on api/src/Entity/Synchronization.php
> +     * @ORM\OneToOne(targetEntity=Entity::class, cascade={"persist", "remove"})
This branch is and should be behind here i think?

2022-08-11 13:27 UTC, WilcoLouwerse commented on api/src/Entity/Synchronization.php
> +     * @ORM\OneToOne(targetEntity=ObjectEntity::class, cascade={"persist", "remove"})
Same as for $entity above^

2022-08-11 13:29 UTC, rjzondervan commented on api/src/Entity/Action.php
> +    private array $throws = [];
It's defaulted by = [];

2022-08-11 13:29 UTC, rjzondervan commented on api/src/Entity/Action.php
> +    private array $conditions = [];
It's defaulted by = [];

2022-08-11 13:29 UTC, rjzondervan commented on api/src/Entity/Action.php
> +    private array $configuration = [];
It's defaulted by = [];

2022-08-11 13:35 UTC, WilcoLouwerse commented on api/src/Service/ResponseService.php
> +                    }
This is something that still contains a bug i need to fix :)
after that we can think about a refactor

2022-08-11 13:37 UTC, WilcoLouwerse commented on api/src/Entity/Action.php
> +    private array $configuration = [];
see comment on $throws

2022-08-11 15:13 UTC, WilcoLouwerse commented on api/src/Service/ResponseService.php
> +                    }
Bug seems to only happen in one specific online installation. not local.
Will look to improve/cleanup this code tomorrow.

2022-08-12 09:26 UTC, rjzondervan reviewed
Still some nesting problems

2022-08-12 09:26 UTC, rjzondervan commented on api/src/Service/ResponseService.php
> +        }
You've still got a lot of nesting levels here, maybe it's better to have three times elseif than an if in an elseif in an if.

2022-08-12 09:26 UTC, rjzondervan commented on api/src/Service/ResponseService.php
> +        }
Same as previous comment, still a large number of nesting levels, making the code complex and not necessarily readable

2022-08-15 10:51 UTC, smisidjan approved these changes

2022-08-15 10:58 UTC, merged